Stdout warn user to name the run
ministry-of-silly-code/experiment_buddy pull request #38
Opened 2021-05-14 19:57 UTC by ioneliabuzatu

At midnight running an experiment and endlessly waiting for the run to launch...

2021-05-20 09:27 UTC, DrTtnk requested changes
Move `logging.info("Name your run in the pop-up window!")` after `import tkinter.simpledialog`, then we are good to go

2021-05-20 09:27 UTC, DrTtnk commented on experiment_buddy/experiment_buddy.py
> +    logging.info("Name your run in the pop-up window!")
This line should be moved inside the try block after importing `tkinter.simpledialog`, given that this is the only case where the popup windows is displayed

2021-05-20 16:44 UTC, manuel-delverme requested changes

2021-05-28 12:26 UTC, ioneliabuzatu commented on setup.py
> +    'GitPython', 'tensorboardX', 'matplotlib', 'wandb', 'fabric', 'cloudpickle', 'PyYaml', 'paramiko', 'tqdm', 'logging'
no :)

2021-05-28 12:30 UTC, merged